### ISSUE TITLE
Support fast_jsonapi

### ISSUE THREAD

**Issue by smarquez1** [davidcelis/api-pagination#102]
I'm trying to paginate a [fast_jsonapi](https://github.com/Netflix/fast_jsonapi) collection in combination with Pagy and getting the following error:

```
NoMethodError Exception: undefined method `count' for #<CheatSheetSerializer:0x00007f2280019448>
```
fast_jsonapi serializers don't provide a `count` method, so the following line is throwing a `NoMethodError`.

https://github.com/davidcelis/api-pagination/blob/master/lib/api-pagination.rb#L67

**Comment by davidcelis** [comment]
@smarquez1 Do you have some example code you could show me? It sounds like you're trying to paginate a `CheatSheetSerializer` as opposed to the actual collection of (presumably) `CheatSheet` records itself. If you need to render a serializer, you should be doing something like:

```ruby
cheat_sheets = paginate(CheatSheat.all)

render json: CheatSheetSerializer.new(cheat_sheets).serializable_hash
```

**Comment by smarquez1** [comment]
Thanks @davidcelis! that seems to be working fine. Do you want me to can make a PR to document this? Or maybe just leaving this issue(closed) will serve.

**Comment by davidcelis** [comment]
@smarquez1 It's already documented in the README (see the second code block in [this section](https://github.com/davidcelis/api-pagination#rails)), but thank you!
