### ISSUE TITLE
problem when migrating from will_paginate to pagy with api-pagination

### ISSUE THREAD

**Issue by MarieS1415** [davidcelis/api-pagination#103]
Hello,
I am trying to migrate from will_paginate to api-pagination, but I encounter the following problem:

I get my collection with the following request:

    @contents = Content.select("distinct on (contents.name) contents.*")
    This request is working and does the expected behavior when run in console.

And I would like to paginate it using api-pagination and pagy:

    @contents = paginate @contents

This triggers the following error:
PG::SyntaxError: ERROR: syntax error at or near "on" LINE 1: SELECT COUNT(distinct on (contents.name) contents.) FROM "c... ^ : SELECT COUNT(distinct on (contents.name) contents.) FROM "contents"

But I cannot see which line it comes from.

It is likely that it does not come from pagy ([issue pagy](https://github.com/ddnexus/pagy/issues/54#issuecomment-399130127))

**Comment by ddnexus** [comment]
https://github.com/ddnexus/pagy/issues/54

**Comment by davidcelis** [comment]
@MarieS1415 Looks like I need to change `.count` to `.count(:all)` here: https://github.com/davidcelis/api-pagination/blob/master/lib/api-pagination.rb#L41

But it also seems like I should just be able to get `count` from the pagy wrapper, so I'll look into that as well.

**Comment by davidcelis** [comment]
@MarieS1415 Would you please try your code with the `master` branch of this gem? I just pushed up a commit that should hopefully fix your issue

**Comment by ddnexus** [comment]
@davidcelis While we have an open issue, I just wanted to inform you that Pagy now has an extra that handles the items per page from the params. Maybe it could simplify the way `api-pagination` handles it. Here is the [items extra doc](https://ddnexus.github.io/pagy/extras/items). Please, let me know if you need more details. Thanks.

**Comment by davidcelis** [comment]
@MarieS1415 I didn't hear back from you, so I've pushed up 4.8.1. If that didn't fix your issue, please let me know and just reopen this

**Comment by MarieS1415** [comment]
Yes now it is working ! 
However when I use a left outer join, the total given in the header is not exact. I used to override the count by using the total_entries option, but it is not working anymore. Should I create a new issue on this topic?

> @contents = paginate @contents, total_entries: @contents.count(:id)
