### ISSUE TITLE
total of elements in headers not correct

### ISSUE THREAD

**Issue by MarieS1415** [davidcelis/api-pagination#106]
Hello,

I am using api_pagination and pagy, and one of the collection I want to paginate is created with a join: therefore the count does not render the correct number of elements. I used to fix it when I used will_paginate by adding a parameter "total_entries" to the paginate function of api_pagination, but it is not working anymore.

`@contents = paginate @contents, total_entries: @contents.count(:id)`

I assume that api-pagination does not transfer this information to pagy to overwrite the count, is it the case?

Thank you !

**Comment by davidcelis** [comment]
@MarieS1415 That's true, there's not currently a way to override the count when using Pagy, but allowing you to pass a `count:` option should be easy enough to support. I'll let you know when that's done

**Comment by davidcelis** [comment]
@MarieS1415 Sorry about that wait, thanks for submitting the PR!
