### ISSUE TITLE
Problem with jbuilder

### ISSUE THREAD

**Issue by tsdbrown** [davidcelis/api-pagination#15]
Hey, I was looking into using your gem, but I can't get it working with jbuilder. Is this something that you'd like the gem to support? If it doesn't.

Unless I'm doing something wrong (entirely possible!) I think it's due to the explicit :json key that gets added to the render options in the "paginate" method.

Rails it only seems to render the jbuilder template if you don't specify a json key in the call to render. e.g. this works:

``` ruby
@collection = some_paginated_collection
render :index, status: :ok
```

but this doesn't:

``` ruby
    render json: @collection
```

Let me know your thoughts. I'd like to help fix it if this is a problem.

**Comment by paulo17** [comment]
It works really well with _paginate_collection. A huge thanks !

**Comment by n8gard** [comment]
I'm trying to use this gem for my API's pagination w/ JBuilder and Kaminari. I've followed this thread but what's not clear is what needs to be added in the JBuilder templates? I have this working controller-side but I'm not seeing anything in the JSON output relative to which page was rendered, etc. I just see that there are, in fact, only two user records output as I'm forcing this via the 'per_page' option (see below). What do I need to do on the JBuilder side to expose the pagination properly?

Here is my controller code for the index action:
```
associated_user_ids = [1,2,3,706]  # just an example. this is an array of legit user_ids for returning
@users = _paginate_collection(User.where(id: associated_user_ids), per_page: 2)
```

**Comment by cseelus** [comment]
@n8gard: Just use it like this with JBuilder:

``` ruby
@users = paginate(User.where(id: associated_user_ids), per_page: 2)

**Comment by januszm** [comment]
@cseelus could you please explain how did you manage to add pagination to the jbuilder template using this gem? I can't get this to

`paginate(...)` in a template (html or json) results in Kaminari rendering the html template always.

**Comment by cseelus** [comment]
I use will_paginate instead of Kaminari and I have specific API controllers which inherit from a `Api::ApiController` that does `include Rails::Pagination`.
