### ISSUE TITLE
APIs are vulnerable to infinite listing with params[:per_page]

### ISSUE THREAD

**Issue by leods92** [davidcelis/api-pagination#22]
I think we should discuss about the `params[:per_page]` that api-pagination makes automatically exposed/allowed when using Grape.
There's currently no limit set what allows anyone to fetch tons of records at once.

What if we add another config option `:max_per_page` that limits that?
I think that we can then make `params[:per_page]` limited to the `:per_page` config by default.

This could break some APIs that rely on `params[:per_page]` to be unlimited.

What should we do?

**Comment by davidcelis** [comment]
From the discussion in #23...

> on a second look, I didn't really see the need to implement a lot of special logic for Rails. The paginate method I have for rails doesn't really care about whats in params. The per_page option you pass in is the final word, so you could change your controller to look something like:

```ruby
class MoviesController < ApplicationController
  MAX_PER_PAGE = 50

  def index
    @movies = Movie.all

    paginate json: @movies, per_page: [params[:per_page], MAX_PER_PAGE].min
  end
end
```

Grape didn't really have a workaround.
