### ISSUE TITLE
Per page in response?

### ISSUE THREAD

**Issue by erikaxel** [davidcelis/api-pagination#26]
Hi,

Hi I'm using the response in this API together with a javascript/HTML pagination library which shows a nice pagination toolbar to the user. However this pagination library needs the per_page to work. I would expect this to be the case with many other libraries/use_cases as well.

Would it be possible to get a per page in the response similar to the total which is provided in the current gem?

I know there are two work arounds:
1) I could probably do something clever and parse it from the link part of the header response. However this seems hackish and a bit unreliable.
2) I could manually set per_page in both my javascript and rails controller code. This is not DRY so I would prefer to avoid it.

**Comment by davidcelis** [comment]
Providing the per_page in the response makes sense to me. I hadn't included it because I figured if people needed it, they had already requested a custom per_page. I didn't take into account people needing to know the default!

**Comment by erikaxel** [comment]
Wow, that was a quick reply and fix! Thank you very much!

**Comment by davidcelis** [comment]
You're welcome! Thanks for the suggestion! There's something else I'm looking into before I cut a release, but you should be able to bundle off of github in the meantime if you need this ASAP.
