### ISSUE TITLE
Multiple rels and urls in the same Link element

### ISSUE THREAD

**Issue by digitaltom** [davidcelis/api-pagination#32]
Api-pagination is adding multiple links and multiple relation types in the 
same Link header which seems not correct as per RFC https://tools.ietf.org/html/rfc5988. 
Check the example in point 5 and description 5.3. 

Shouldn't it look like this?
```
Link: <http://localhost:3000/movies?page=1>; rel="first"
Link: <http://localhost:3000/movies?page=173>; rel="last"
Link: <http://localhost:3000/movies?page=6>; rel="next"
Link: <http://localhost:3000/movies?page=4>; rel="prev"
```

**Comment by davidcelis** [comment]
Multiple links each with their own relation type in the header are fine, as long as they are comma delimited. Having the same header multiple times with different values would not be a valid HTTP request or response. There's an example on that same RFC right before section 6:

```
Link: </TheBook/chapter2>;
         rel="previous"; title*=UTF-8'de'letztes%20Kapitel,
         </TheBook/chapter4>;
         rel="next"; title*=UTF-8'de'n%c3%a4chstes%20Kapitel
```

So you have the basic structure...

Link: <URI>; rel="one", <URI>; rel="two", <URI>; rel="three", etc...

**Comment by digitaltom** [comment]
Ok, thanks for the explanation!
