### ISSUE TITLE
how to use Grape::Entity in api-pagination?

### ISSUE THREAD

**Issue by 85636682** [davidcelis/api-pagination#38]
```
desc "最新Tweet 验证：是 可选参数：:page 返回第page页的数据 and :per_page 每页返回per_page条数据 默认5条"
    paginate per_page: 5, max_per_page: 20
    get do
      authenticate!
      #present current_user.feed, with: APIEntities::Tweet
      paginate current_user.feed, with: APIEntities::Tweet
    end
```
this has a error
```
ArgumentError (wrong number of arguments (2 for 1)):
```

**Comment by eidge** [comment]
```present paginate(current_user.feed), with: APIEntities::Tweet```

You still need to call present, paginate will only scope your query.

**Comment by davidcelis** [comment]
@eidge is right; the Grape pagination just scopes the query and sets up headers. You'll still need to use your own presenter if you want. Thanks, @eidge!

**Comment by 85636682** [comment]
@eidge , @davidcelis thanks for your help!
