### ISSUE TITLE
work with Array type

### ISSUE THREAD

**Issue by deepsystm** [davidcelis/api-pagination#39]
please add `Array` type support for `pagination`

**Comment by nddeluca** [comment]
I believe this gem support array pagination with the `Kaminari` gem out of the box.  If you are using the `will_paginate` gem then all you should have to do is add `require 'will_paginate/array'` to your application.

**Comment by deepsystm** [comment]
Thanks! Found it in readme

**Comment by davidcelis** [comment]
Sounds like this is figured out!
