### ISSUE TITLE
Support will_paginate's config

### ISSUE THREAD

**Issue by Lacrymology** [davidcelis/api-pagination#48]
is there a reason not to support will_paginate's (and I guess kaminari's as well, but I haven't used that) pagination options?

e.g.

```ruby
class Post
  self.per_page = 2
end

paginate Post.all
```

but in the response headers I get

```
Per-Page: 30
```

**Comment by Lacrymology** [comment]
Or else: is it possible to somehow set the limit in a per-resource basis, rather than globally?

**Comment by davidcelis** [comment]
There's no reason; global support of Kaminari's and WillPaginate's configuration was added in #20 but nobody's tackled grabbing a model's configuration yet.

**Comment by JiriChara** [comment]
Kaminari allows following:
```
class User < ActiveRecord::Base
  paginates_per 50
end
```

which sets `User.default_per_page` to `50`. I think I might have a "simple" solution for both will_paginate and kaminari, but I am waiting with PR for #56 to get merged so I don't have to deal with merge conflicts :dizzy_face:
