### ISSUE TITLE
Option to create https links in headers

### ISSUE THREAD

**Issue by pranav7** [davidcelis/api-pagination#49]
Is there an option to force https headers for the links?

**Comment by pranav7** [comment]
I see that you use `request.original_url` to fetch the url of the current request to make header links.
https://github.com/davidcelis/api-pagination/blob/master/lib/rails/pagination.rb#L34

However, in our production environment even if the request is made to `https` the links that are made are `http`.

Orignal Request `https://example.com/api/products`
```
Link → <http://example.com/api/products?page=7>; rel="last", <http://example.com/api/products?page=2>; rel="next"
```

**Comment by pranav7** [comment]
Ok, found the solution.

http://blog.seancarpenter.net/2013/09/02/rails-ssl-route-generation-with-nginx-and-unicorn/

**Comment by davidcelis** [comment]
Glad you got it! :grinning:
