### ISSUE TITLE
Not paginating when using each_serializer

### ISSUE THREAD

**Issue by oyeanuj** [davidcelis/api-pagination#53]
Hi @davidcelis! This might be a n00b mistake but in my setup, I can't get the pagination to work when using `each_serializer` option. In other words, if I do `API_URL?page=2`, it returns the same set of results. 

I am using Rails 4.2.4 with AMS 0.9.3 and Kaminari. Here is the relevant code in the controller: 

```
paginate json: 		posts,
each_serializer: 	PostSerializer,
page: 			params[:page],
per_page: 		20
```

If I comment out `each_serializer` above, then it works fine.

Any pointers would be helpful, and thank you again for the gem!

**Comment by davidcelis** [comment]
Hey @oyeanuj, are you explicitly using the `rails-api` gem? If so it should work fine. Another thing you could try is just calling `paginate` with the collection itself and rendering with the serializer later, as per the README:

```ruby
posts = paginate posts, page: params[:page], per_page: 20

render json: PostSerializer.new(posts)
```

**Comment by oyeanuj** [comment]
Thanks for the quick response! I am explicitly using `rails-api` gem. 

Also, I had tried what you suggested earlier and got this:

```
NoMethodError at /api/feed
====================================

> undefined method `read_attribute_for_serialization' for #
<Kaminari::PaginatableArray:0x007ffa37da0488>
```

Any ideas on what the issue might be?

**Comment by davidcelis** [comment]
Ah, I guess ActiveModel::Serializers are designed to just take a single record? You'd probably have to do something like `posts.map { |post| PostSerializer.new(post) }`

**Comment by davidcelis** [comment]
So I just created a bare Rails API with the latest version of api-pagination (4.2.0), scaffolded a model with a serializer, and tried passing `each_serializer` in. It worked just fine… I'm going to assume that whatever issue this may have been was fixed in the version I just pushed. Mind trying it out? Otherwise, it must be a problem in your Rails app…

**Comment by oyeanuj** [comment]
Yes, its working now with the upgraded version. Thanks so much!
