### ISSUE TITLE
Is there a default sort order on :id enforced?

### ISSUE THREAD

**Issue by n8gard** [davidcelis/api-pagination#54]
I'm specifying that records get sorted by name but what I'm seeing is that the paginated result set is being ordered by :id, :name. Is this expected? It seems that it prevents any sorting at all which would make me sad. If I'm missing something, it isn't obvious. Please advise.
```ruby
      def index
        pp sort_order  #=> :name
        @users = _paginate_collection(User.where(id: associated_user_ids).order(sort_order),
                                      per_page: pagination_items_per_page,
                                      page: page_requested)
      end
```

Results in SQL:
```SQL
User Load (0.9ms)  SELECT  "users".* FROM "users" WHERE "users"."id" IN (1, 2, 3, 5, 6,... 288)  ORDER BY "users"."id" ASC, "users"."name" ASC LIMIT 50 OFFSET 0
```

**Comment by davidcelis** [comment]
Hey, I suspect this is actually a combination of the `WHERE "users"."id" IN (…)` clause and the `ORDER BY "users"."id" ASC` not behaving correctly as opposed to the pagination. If you try that query manually, but remove the `LIMIT 50 OFFSET 0`, what happens?

**Comment by n8gard** [comment]
You are, indeed, correct, sir. Closing this issue. Apologies.
```ruby
def index
        pp sort_order  #=> :name
        #@users = _paginate_collection(User.where(id: associated_user_ids).order(sort_order),
        #                              per_page: pagination_items_per_page,
        #                              page: page_requested)
           @users = User.where(id: associated_user_ids).order(sort_order)
      end
```
produces same result sorting by :id, :name.

**Comment by n8gard** [comment]
Just to share information and after thinking this was ActiveRecord weirdness associated with sending an array of IDs into the where clause... extra digging found our problem was a default_scope on the User model. Upon removing it, the primary sort via :id disappeared and we got paginated results by :name. Again, sorry for the trouble,
