### ISSUE TITLE
Configuration from readme not working

### ISSUE THREAD

**Issue by JerryGreen** [davidcelis/api-pagination#58]
I just copied full configuration from readme, moved it to `initializers` folder and got this:

```
/config/initializers/api-pagination.rb:15:in `block in <top (required)>': undefined method `page_param=' for #<ApiPagination::Configuration:0x00000001fa6210> (NoMethodError)
Did you mean?  page_header=
```

_P.S. After that I figured out I don't need the configuration for this gem. Actually I needed configuration for kaminari (to change default of `per_page`). But keep in mind there is a problem with configuration file (or you have to add some explanation to readme if it's not obviously to use that)._

**Comment by davidcelis** [comment]
Looks like there's a discrepancy between the README (which is for the master branch) and what the current release is. Which is a good reminder for me to cut a new release. I'll try to do that tomorrow. Thanks!

**Comment by JerryGreen** [comment]
@davidcelis I see. Thx for your gem!
