### ISSUE TITLE
Edge cases when records change in the middle of paginating

### ISSUE THREAD

**Issue by ajb** [davidcelis/api-pagination#60]
Here's a pretty good description: http://stackoverflow.com/questions/13872273/api-pagination-best-practices

> Like many APIs, this one paginates large results. If you query /foos, you'll get 100 results (i.e. foo #1-100), and a link to /foos?page=2 which should return foo #101-200.

> Unfortunately, if foo #10 is deleted from the data set before the API consumer makes the next query, /foos?page=2 will offset by 100 and return foos #102-201.

> This is a problem for API consumers who are trying to pull all foos - they will not receive foo #101.

I'm not sure if I believe that `api-pagination` should handle this out-of-the-box, but I'm trying to automatically append an `?until=TIMESTAMP` parameter to my `Link` header, and I've ended up with a pretty terrible monkeypatch: 

![img](http://take.ms/ZLc22)

I'm wondering if the author / maintainers have thought about this at all, and what would be an acceptable solution?

**Comment by davidcelis** [comment]
Hey @ajb, sorry it's taken me so long to respond to this issue 😓

> I'm not sure if I believe that `api-pagination` should handle this out-of-the-box

This is my feeling, to be honest. I think that this is simply a limitation of Link header pagination that may be okay for some and not for others. One thought I've had is that perhaps this is a great case for [Range header pagination](http://otac0n.com/blog/2012/11/21/range-header-i-choose-you.html) where the ranges provided are the record's IDs as opposed to an arbitrary order of "this element is first, this is second, etc". But, of course, that only works for items that have numeric IDs. How do you request a range of UUIDs?

Anyway, this is a problem that anybody using Kaminari or WillPaginate will have. It's an issue with the underlying paginators, unfortunately. A solution would be for them to use `WHERE` based pagination queries as opposed to the more standard `LIMIT`/`OFFSET` queries… Hopefully that's helpful!
