### ISSUE TITLE
Access pagination details in json

### ISSUE THREAD

**Issue by samjbmason** [davidcelis/api-pagination#61]
While its great to have the pagination inside the headers, is it possible to render out these details such as `next_page_url`, `total_items` in the json view?

I tried using kaminari's `page` local var but it wasnt available.

**Comment by davidcelis** [comment]
Hey @samjbmason. This currently isn't supported by the api-pagination gem, and I'm unlikely to add support for it in the future. The purpose of the api-pagination gem is stated in the README:

> Paginate in your headers, not in your response body. This follows the proposed [RFC-5988](http://tools.ietf.org/html/rfc5988) standard for Web linking.

For now, I'll be continuing to designate this gem as a solution solely to paginate in the headers and not the response body.
