### ISSUE TITLE
ActionView::MissingTemplate when passing in the template or action options

### ISSUE THREAD

**Issue by codeodor** [davidcelis/api-pagination#64]
Code looks like this:

```ruby
module Api
  module V1
    class TeamsController < ApiController
      def mine
        @teams = current_user.teams
        paginate @teams, action: 'index'
      end
    end
  end
end
```

If I change it to `render` and drop the collection, it renders as expected (minus the headers this gem adds). However, if I try to paginate, it all of the sudden looks for the `mine` template instead of the specified `index` template.

If I change it to `paginate json: @teams, action: 'index'` it does not use my template at all, resulting in an information leak (I'm assuming it just calls `as_json` on the AR collection).

**Comment by davidcelis** [comment]
Hey @codeodor, thanks for reporting this! If it's not too much trouble, is the source of your Rails app by chance shareable? If not, would it be possible to whip up a quick template Rails app or something similar that I can spin up to more quickly debug this?

**Comment by codeodor** [comment]
It's not sharable, but I'm pretty early on in the development of the API, so if it's not something super specific to my app, I ought to be able to whip up something fairly quickly. 

I'll see what I can get you tomorrow morning (US Central).

**Comment by codeodor** [comment]
Here's an example app that demonstrates the issue: https://github.com/codeodor/api-pagination-failure-reproduction

**Comment by davidcelis** [comment]
Thanks @codeodor! I'll take a look in the next few days; I'm on vacation right now ;)

**Comment by davidcelis** [comment]
Ahh I see what you're talking about, @codeodor. If you check [the README's Rails section](https://github.com/davidcelis/api-pagination#rails), the bottom goes over how to use `paginate` if you need more custom behavior. You can pass your collection directly to `paginate` to set your headers and receive the paginated collection back so that you can do whatever you need with it. I'd recommend changing your code to the following:

```ruby
module Api
  module V1
    class TeamsController < ApiController
      def mine
        @teams = paginate(current_user.teams)
        render action: 'index' # or…
        # render template: 'teams/template'
      end
    end
  end
end
```

I may change `paginate` to be a bit more convenient for things like this but, as it stands now, the option parsing and implicit calls to `render` are already a bit complicated. If this doesn't work, feel free to reopen the issue.

**Comment by codeodor** [comment]
Thanks. That worked!

I think I got confused by this part:

> In its most convenient form, paginate simply mimics render
> ... shows example here ...
> This will pull your collection from the json or xml option, paginate it for you using params[:page] and params[:per_page], render Link headers, and call ActionController::Base#render with whatever you passed to paginate

I might take a look later and see if there's an easy win that acceptable as a PR to make that either more clear or more correct when it comes to the template option.

Thanks for the awesome gem and pointing out the fix for me!

**Comment by davidcelis** [comment]
Gotcha, looks like that documentation could be improved too. It mimics calls to `render` when the `json` or `xml` options are passed 😅

**Comment by codeodor** [comment]
Ok, after looking at it for a while this morning, I see there's no real way to make it behave like Rails without breaking changes, or just introducing a new method. Because of that, I don't see a need for me to send a PR to adjust it. 

Thanks again for your work!
