### ISSUE TITLE
Undefined method paginate on Rails 5.0.1

### ISSUE THREAD

**Issue by ketiko** [davidcelis/api-pagination#76]
```NoMethodError - undefined method `paginate' for #<UsersController:0x007fedd643de08>:```

It seems to be because in Rails 5, ActionContoller::API is defined in a standard `rails new dummy` application.

So https://github.com/davidcelis/api-pagination/blob/master/lib/api-pagination/hooks.rb#L8 works for rails api only applications, but not regular rails applications.

It seems that since both ActionController::Base and ActionController::API inherit from ActionController::Metal, maybe that would be a better place to add the hook.

**Comment by davidcelis** [comment]
Yep, please see the [release notes for 4.5.0](https://github.com/davidcelis/api-pagination/releases/tag/v4.5.0). Sorry for the trouble!

**Comment by ketiko** [comment]
Doh sorry I missed that in the notes. Looks like it's also in the readme. Helps if I read the readme lol. Thanks, I really love this gem!
