### ISSUE TITLE
Group json data

### ISSUE THREAD

**Issue by mayordwells** [davidcelis/api-pagination#87]
How can I group json data by table name, e.g, name or sku? 
```
# method 1
def product_data
    products = paginate Product.all, per_page: 20
    render json: JSON.pretty_generate(product_data.as_json)
  end
```
The above method produced the following, please click link to check - [https://deaninfotech.herokuapp.com/products.json](https://deaninfotech.herokuapp.com/products.json)

I want to be able to group the products by sku or by name? How can I get a work around it?

I wrote this method, which didn't give the desired result
```
# method 2
def product_data
    products = paginate Product.all, per_page: 20
    grouped_products = products.group_by{ |product| product['name']['AP'] }.values
    product_data = grouped_products
    render json: JSON.pretty_generate(product_data.as_json)
  end
```
The desired result is that I want to be able to group all Products in the database, even before paginating them. 

The reason why it is necessary to group the objects before paginating is that I noticed after grouping with `method 2` above, I found that the objects were not fully grouped together. 
Next page is showing more products from an already grouped object in the previous page.

I want to render the returned grouped products, and then paginate it into 20 grouped products per page. 

How can I achieve this result, please? 

I read some post that suggested Filtering and Grouping objects in the database in postgres before actually sending it to rails. But still, don't know how to achieve this. Any help or links would be appreciated, thanks.

**Comment by davidcelis** [comment]
Hi! This unfortunately isn’t really an api-pagination question, so I’m going to close the issue. I think you’ll find what you’re looking for in Rails’ querying and filtering guide, though: http://guides.rubyonrails.org/active_record_querying.html

If not, this would be a good StackOverflow question!
