### ISSUE TITLE
Support for Pagy

### ISSUE THREAD

**Issue by cseelus** [davidcelis/api-pagination#97]
[Pagy](https://github.com/ddnexus/pagy) is a new "pagination gem that outperforms the others in each and every benchmark and comparison".

Would this paginator be something api-pagination could support?

**Comment by davidcelis** [comment]
Yup, this is on my radar! Stay tuned, hope to have something out soon.

**Comment by davidcelis** [comment]
I've pushed up version 4.8.0 which adds support for Pagy. I don't have an app using Pagy yet, so please let me know if you encounter any problems!

**Comment by cseelus** [comment]
Nice, works exactly as expected. Thanks for the quick implementation and publication on RubyGems.
